[package]
name = "cryptoexch"
version = "0.1.0"
authors = ["gwierzchowski <gwierzchowski@wp.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# default = ["bitbay", "csv_out", "pb_out"]

# Enables support for https://bitbay.net
bitbay = []

# Enables support for CSV output format
csv_out = ["csv"]

# Enables support for Protocol Buffers output format
pb_out = ["protobuf", "protobuf-codegen-pure"]

[dependencies]
actix = "0.9"
actix-rt = "1.1"
anyhow = "1"
async-trait = "0.1"
chrono = "0.4"
csv = { version = "1.1", optional = true }
lazy_static = "1.4"
# quick-protobuf = { version = "0.7", optional = true }
protobuf = { version = "2", optional = true }
regex = "1.3"
reqwest = { version = "0.10", features = ["blocking", "json"] }
rhai = { version = "0.17.0", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
tokio = { version = "0.2", features = ["fs", "io-util"] }

[build-dependencies]
protobuf-codegen-pure = { version = "2", optional = true }
