[package]
name = "cryptoexch"
version = "0.1.0"
authors = ["gwierzchowski <gwierzchowski@wp.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
actix-rt = "1.1"
anyhow = "1"
async-trait = "0.1"
chrono = "0.4"
csv = "1.1"
# futures = "0.3"
# futures-util = "0.3"
lazy_static = "1.4"
# quick-protobuf = "0.7"
protobuf = "2"
regex = "1.3.9"
reqwest = { version = "0.10", features = ["blocking", "json"] }
rhai = { version = "0.15", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
tokio = { version = "0.2", features = ["fs", "io-util"] }

[build-dependencies]
protobuf-codegen-pure = "2"
